import {jest} from '@jest/globals';
import {createOAuth} from '../src/oauth.mjs';

const client={client_id:'funnel-mcp',redirect_uris:'["https://funnel.purinton.us/callback"]',allowed_scopes:'["funnel:read","funnel:write"]',allowed_resources:'["https://funnel.purinton.us/mcp"]'};
const setup=({code,token}={})=>{const db={execute:jest.fn(async sql=>{if(sql.startsWith('SELECT * FROM oauth_clients'))return [[client]];if(sql.startsWith('SELECT * FROM oauth_codes'))return [[code].filter(Boolean)];if(sql.startsWith('SELECT * FROM oauth_tokens'))return [[token].filter(Boolean)];return [[]]})};return {db,oauth:createOAuth(db)};};

test('MCP authorization binds resource and enforces scopes',async()=>{const {db,oauth}=setup();const result=await oauth.authorize({client_id:'funnel-mcp',response_type:'code',redirect_uri:'https://funnel.purinton.us/callback',code_challenge:'abc',code_challenge_method:'S256',scope:'funnel:read',resource:'https://funnel.purinton.us/mcp',state:'s'},'u1');expect(result).toContain('code=');expect(db.execute.mock.calls[1][1][6]).toBe('https://funnel.purinton.us/mcp');expect(db.execute.mock.calls[1][1][5]).toBe('funnel:read');});

test('MCP authorization rejects unknown or unauthorized scope/resource',async()=>{const {oauth}=setup();await expect(oauth.authorize({client_id:'funnel-mcp',response_type:'code',redirect_uri:'https://funnel.purinton.us/callback',code_challenge:'abc',code_challenge_method:'S256',scope:'openid',resource:'https://funnel.purinton.us/mcp'},'u1')).rejects.toMatchObject({error:'invalid_scope'});await expect(oauth.authorize({client_id:'funnel-mcp',response_type:'code',redirect_uri:'https://funnel.purinton.us/callback',code_challenge:'abc',code_challenge_method:'S256',scope:'funnel:read',resource:'https://other.example/mcp'},'u1')).rejects.toMatchObject({error:'invalid_target'});});

test('token exchange rejects changed resource and returns bound resource',async()=>{const verifier='test-verifier';const {oauth}=setup({code:{id:'c1',client_id:'funnel-mcp',user_id:'u1',redirect_uri:'https://funnel.purinton.us/callback',scope:'funnel:read',resource:'https://funnel.purinton.us/mcp',code_challenge:(await import('../src/crypto.mjs')).pkce(verifier)}});const bad=await oauth.token({grant_type:'authorization_code',code:'c',client_id:'funnel-mcp',redirect_uri:'https://funnel.purinton.us/callback',code_verifier:verifier,resource:'https://other.example/mcp'});expect(bad.error).toBe('invalid_grant');const good=await oauth.token({grant_type:'authorization_code',code:'c',client_id:'funnel-mcp',redirect_uri:'https://funnel.purinton.us/callback',code_verifier:verifier,resource:'https://funnel.purinton.us/mcp'});expect(good.resource).toBe('https://funnel.purinton.us/mcp');});
