import {jest} from '@jest/globals';

jest.unstable_mockModule('../src/oidc-keys.mjs',()=>({loadSigningKey:jest.fn(async()=>({kid:'k',privateKey:'p'})),signJwt:jest.fn(()=> 'jwt')}));
const {createOAuth}=await import('../src/oauth.mjs');
const {pkce}=await import('../src/crypto.mjs');

const client={client_id:'c',redirect_uris:'["https://client.example/cb"]',allowed_scopes:'["funnel:read","funnel:write","openid"]',allowed_resources:'["https://funnel.purinton.us/mcp"]'};
const makeDb=({clientRow=client,code,token,users=[],groups=[],groupError=false}={})=>{let n=0;const db={execute:jest.fn(async(sql)=>{if(sql.startsWith('SELECT * FROM oauth_clients'))return [[clientRow].filter(Boolean)];if(sql.startsWith('SELECT * FROM oauth_codes'))return [[code].filter(Boolean)];if(sql.startsWith('SELECT * FROM oauth_tokens'))return [[token].filter(Boolean)];if(sql.startsWith('SELECT username,email'))return [users];if(sql.startsWith('SELECT group_name')){if(groupError)throw Error('groups');return [groups];} n++; return [[]]})};return {db,oauth:createOAuth(db),n:()=>n};};
const auth=(extra={})=>({client_id:'c',response_type:'code',redirect_uri:'https://client.example/cb',code_challenge:'abc',code_challenge_method:'S256',scope:'funnel:read',...extra});

beforeEach(()=>{delete process.env.OAUTH_PROTECTED_RESOURCES;delete process.env.OAUTH_SCOPES;delete process.env.OAUTH_DCR_SCOPES;delete process.env.OAUTH_DCR_RESOURCES;});

test('resourceUri and authorization validation branches',async()=>{const {oauth}=makeDb();const {oauth:missing}=makeDb({clientRow:null});expect(oauth.resourceUri('https://x.test/a')).toBe('https://x.test/a');for(const x of ['http://x','https://x/a?x=1','https://x/a#h','bad', 'x'.repeat(2049)])expect(oauth.resourceUri(x)).toBeNull();
 await expect(missing.authorize(auth({client_id:'bad'}),'u')).rejects.toMatchObject({error:'invalid_request'});
 for(const q of [auth({response_type:'token'}),auth({redirect_uri:''}),auth({code_challenge:''}),auth({code_challenge_method:'plain'})]) await expect(oauth.authorize(q,'u')).rejects.toMatchObject({error:'invalid_request'});
 await expect(oauth.authorize(auth({resource:'bad'}),'u')).rejects.toMatchObject({error:'invalid_target'});
 await expect(oauth.authorize(auth({scope:'nope',resource:'https://funnel.purinton.us/mcp'}),'u')).rejects.toMatchObject({error:'invalid_scope'});
});

test('authorization resource and scope paths',async()=>{const {oauth,db}=makeDb();await expect(oauth.authorize(auth({resource:'https://other.test/mcp'}),'u')).rejects.toMatchObject({error:'invalid_target'});await expect(oauth.authorize(auth({resource:'https://funnel.purinton.us/mcp'}),'u')).resolves.toContain('state=');expect(db.execute).toHaveBeenCalled();
 const {oauth:o2}=makeDb({clientRow:{...client,allowed_resources:'[]'}});await expect(o2.authorize(auth({resource:undefined,scope:''}),'u')).resolves.toContain('code=');
});

test('configured scope/resource and edge branches',async()=>{process.env.OAUTH_SCOPES='funnel:read';process.env.OAUTH_PROTECTED_RESOURCES='["https://funnel.purinton.us/mcp"]';const {oauth}=makeDb({clientRow:{...client,allowed_scopes:'[]',allowed_resources:'[]'}});await expect(oauth.authorize(auth({resource:'https://funnel.purinton.us/mcp',scope:'funnel:read'}),'u')).resolves.toContain('code=');process.env.OAUTH_SCOPES='{bad';process.env.OAUTH_PROTECTED_RESOURCES='{bad';const {oauth:o2}=makeDb({clientRow:{...client,allowed_scopes:'not-json',allowed_resources:''}});await expect(o2.authorize(auth({resource:undefined,scope:''}),'u')).resolves.toContain('code=');});

test('registration rejects metadata and accepts valid clients',async()=>{const {oauth,db}=makeDb();for(const body of [null,{}, {client_name:'x',redirect_uris:[]},{client_name:'x',redirect_uris:['http://bad.test','bad']},{client_name:'x',redirect_uris:['https://x'],token_endpoint_auth_method:'client_secret_basic'},{client_name:'x',redirect_uris:['https://x'],grant_types:['refresh_token']},{client_name:'x',redirect_uris:['https://x'],response_types:['token']},{client_name:'x',redirect_uris:['https://x'],code_challenge_methods_supported:['plain']},{client_name:'x',redirect_uris:['https://x'],scope:'bad'},{client_name:'x',redirect_uris:['https://x'],resource:'https://other'}]) expect((await oauth.register(body)).error).toBeTruthy();
 const out=await oauth.register({client_name:' App ',redirect_uris:['https://x'],grant_types:['authorization_code','refresh_token'],scope:'funnel:read funnel:read'});expect(out.client_name).toBe('App');expect(out.scope).toBe('funnel:read');expect(db.execute).toHaveBeenCalledTimes(2);
 for(const uri of ['http://127.0.0.1/','http://127.0.0.1:33418','http://localhost:33418','https://vscode.dev/redirect'])expect((await oauth.register({client_name:'x',redirect_uris:[uri]})).client_id).toMatch(/^dcr_/);
});

test('authorization-code token errors and success',async()=>{const verifier='v';const base={id:'id',client_id:'c',user_id:'u',redirect_uri:'https://client.example/cb',scope:'funnel:read',resource:'https://funnel.purinton.us/mcp',code_challenge:pkce(verifier)};const {oauth,db}=makeDb({code:base});
 for(const b of [{grant_type:'authorization_code'},{grant_type:'authorization_code',code:'x',client_id:'bad',redirect_uri:base.redirect_uri,code_verifier:verifier},{grant_type:'authorization_code',code:'x',client_id:'c',redirect_uri:'wrong',code_verifier:verifier},{grant_type:'authorization_code',code:'x',client_id:'c',redirect_uri:base.redirect_uri,code_verifier:'bad'}])expect((await oauth.token(b)).error).toBe('invalid_grant');
 expect((await oauth.token({grant_type:'authorization_code',code:'x',client_id:'c',redirect_uri:base.redirect_uri,code_verifier:verifier,resource:'wrong'})).error).toBe('invalid_grant');const out=await oauth.token({grant_type:'authorization_code',code:'x',client_id:'c',redirect_uri:base.redirect_uri,code_verifier:verifier,resource:base.resource});expect(out.access_token).toBeTruthy();expect(db.execute.mock.calls.some(x=>x[0].startsWith('UPDATE oauth_codes'))).toBe(true);
});

test('refresh and unsupported token paths',async()=>{const row={id:'t',client_id:'c',user_id:'u',scope:'funnel:read',family_id:'f',resource:'https://funnel.purinton.us/mcp',nonce:null};const {oauth,db}=makeDb({token:row});expect((await oauth.token({grant_type:'refresh_token',refresh_token:'x',client_id:'c'})).refresh_token).toBeTruthy();expect((await oauth.token({grant_type:'refresh_token',refresh_token:'x',client_id:'bad'})).error).toBe('invalid_grant');expect((await oauth.token({grant_type:'refresh_token',refresh_token:'x',client_id:'c',resource:'other'})).error).toBe('invalid_grant');const out=await oauth.token({grant_type:'refresh_token',refresh_token:'x',client_id:'c',resource:row.resource});expect(out.refresh_token).toBeTruthy();expect(db.execute.mock.calls.some(x=>x[0].startsWith('UPDATE oauth_tokens'))).toBe(true);expect((await oauth.token({grant_type:'x'})).error).toBe('unsupported_grant_type');});

test('openid issue includes optional claims and tolerates group failure',async()=>{const row={id:'id',client_id:'c',user_id:'u',redirect_uri:'https://client.example/cb',scope:'openid',code_challenge:pkce('v'),nonce:'n'};const {oauth}=makeDb({code:row,users:[{username:'alice',email:'a@x',display_name:'Alice',email_verified:1}],groups:[{group_name:'admin'}]});const out=await oauth.token({grant_type:'authorization_code',code:'x',client_id:'c',redirect_uri:row.redirect_uri,code_verifier:'v'});expect(out.id_token).toBe('jwt');
 const {oauth:o2}=makeDb({code:{...row,user_id:'u2'},users:[],groupError:true});const out2=await o2.token({grant_type:'authorization_code',code:'x',client_id:'c',redirect_uri:row.redirect_uri,code_verifier:'v'});expect(out2.id_token).toBe('jwt');const {oauth:o3}=makeDb({code:{...row,nonce:null},users:[]});expect((await o3.token({grant_type:'authorization_code',code:'x',client_id:'c',redirect_uri:row.redirect_uri,code_verifier:'v',resource:row.resource})).id_token).toBe('jwt');});
