CREATE TABLE IF NOT EXISTS oauth_users (
  id VARCHAR(32) PRIMARY KEY, username VARCHAR(191) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS oauth_clients (
  id VARCHAR(32) PRIMARY KEY, client_id VARCHAR(128) NOT NULL UNIQUE, client_secret_hash CHAR(64), name VARCHAR(191) NOT NULL,
  redirect_uris JSON NOT NULL, public_client BOOLEAN NOT NULL DEFAULT TRUE, allowed_scopes TEXT NOT NULL DEFAULT '[]', allowed_resources TEXT NOT NULL DEFAULT '[]', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS oauth_codes (
  id VARCHAR(32) PRIMARY KEY, code_hash CHAR(64) NOT NULL UNIQUE, client_id VARCHAR(128) NOT NULL, user_id VARCHAR(32) NOT NULL,
  redirect_uri VARCHAR(2048) NOT NULL, scope VARCHAR(2048) NOT NULL, resource VARCHAR(2048) NULL, code_challenge VARCHAR(128) NOT NULL, code_challenge_method VARCHAR(10) NOT NULL,
  expires_at DATETIME NOT NULL, used_at DATETIME NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX(code_hash), INDEX(expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS oauth_tokens (
  id VARCHAR(32) PRIMARY KEY, token_hash CHAR(64) NOT NULL UNIQUE, token_type ENUM('access','refresh') NOT NULL, client_id VARCHAR(128) NOT NULL,
  user_id VARCHAR(32) NOT NULL, scope VARCHAR(2048) NOT NULL, resource VARCHAR(2048) NULL, expires_at DATETIME NOT NULL, revoked_at DATETIME NULL, family_id VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(token_hash), INDEX(expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS oauth_sessions (
  id VARCHAR(64) PRIMARY KEY, user_id VARCHAR(32) NOT NULL, session_type VARCHAR(16) NOT NULL,
  expires_at DATETIME NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(expires_at), INDEX(user_id,session_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS oauth_pkce_flows (
  state_hash CHAR(64) PRIMARY KEY, verifier VARCHAR(128) NOT NULL, redirect_uri VARCHAR(2048) NOT NULL,
  expires_at DATETIME NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS oauth_rate_limits (
  bucket_key VARCHAR(255) PRIMARY KEY, count INT UNSIGNED NOT NULL, reset_at DATETIME(3) NOT NULL, INDEX(reset_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
