import bcrypt from 'bcryptjs';
import {randomToken} from './crypto.mjs';
import {envNumber, rateLimit} from './rate-limit.mjs';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cookies=v=>Object.fromEntries((v||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2));
const page=b=>`<!doctype html><meta name=viewport content="width=device-width"><title>Elid Account</title><style>:root{color-scheme:dark}body{font:15px system-ui;max-width:900px;margin:auto;padding:1rem;background:#111;color:#eee}nav,.card{background:#1d1d1d;border:1px solid #444;border-radius:10px;padding:1rem;margin:1rem 0}nav{display:flex;justify-content:space-between}input,button{padding:.6rem;margin:.2rem;border-radius:5px;border:1px solid #667085;background:#111;color:#fff}button{background:#4f8cff;border:0;cursor:pointer}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:.6rem;border-bottom:1px solid #444}.error{color:#ff9b9b}.ok{color:#8dffb0}</style>${b}`;
export function mountAccount(app,db){
 const auth=async(req,res,next)=>{const t=cookies(req.headers.cookie).elid_account;const [ss]=await db.execute("SELECT user_id id,expires_at FROM oauth_sessions WHERE id=? AND session_type='account' AND expires_at>NOW()",[t]);const s=ss[0];if(!s)return res.redirect('/account/login');req.user=s;next()};
 app.get('/account/login',(q,r)=>r.send(`<!doctype html><meta name=viewport content="width=device-width"><title>Sign in - Elid</title><style>:root{color-scheme:dark}body{font:15px system-ui;min-height:100vh;display:grid;place-items:center;margin:0;background:radial-gradient(circle at top,#24334b,#111 60%);color:#eee}.card{width:min(420px,calc(100% - 2rem));box-sizing:border-box;background:#1d1d1dcc;border:1px solid #4b5563;border-radius:14px;padding:2rem;box-shadow:0 20px 70px #0008}h1{margin:.2rem 0 .5rem;font-size:1.8rem}.muted{color:#aaa;line-height:1.5}label{display:block;margin:1rem 0 .35rem}input{box-sizing:border-box;width:100%;padding:.75rem;border:1px solid #667085;border-radius:6px;background:#111;color:#fff;font-size:1rem}button{width:100%;padding:.75rem;margin-top:1.3rem;border:0;border-radius:6px;background:#4f8cff;color:#fff;font-weight:600;font-size:1rem;cursor:pointer}button:hover{background:#6b9dff}.brand{color:#8db7ff;font-weight:700;letter-spacing:.04em}</style><main class=card><div class=brand>ELID ACCOUNT</div><h1>Sign in to Elid</h1><p class=muted>Manage your account and authorized applications.</p><form method=post><label>Username</label><input name=username autocomplete=username required autofocus><label>Password</label><input name=password type=password autocomplete=current-password required><button>Sign in</button></form></main>`));
 app.post('/account/login',rateLimit({db,windowMs:envNumber('ACCOUNT_LOGIN_RATE_WINDOW_MS',900000),max:envNumber('ACCOUNT_LOGIN_RATE_MAX',30),message:'Too many login attempts; retry in 15 minutes'}),async(q,r)=>{const [x]=await db.execute('SELECT id,username,password_hash FROM oauth_users WHERE username=?',[q.body.username]);if(!x[0]||!(await bcrypt.compare(q.body.password,x[0].password_hash)))return r.status(401).send(page('<main class=card><p class=error>Invalid username or password.</p><a href=/account/login>Try again</a></main>'));const t=randomToken();await db.execute("INSERT INTO oauth_sessions(id,user_id,session_type,expires_at) VALUES(?,?,?,DATE_ADD(NOW(),INTERVAL 1 DAY))",[t,x[0].id,'account']);r.setHeader('Set-Cookie',`elid_account=${encodeURIComponent(t)}; HttpOnly; SameSite=Strict; Path=/account; Max-Age=86400${q.secure?'; Secure':''}`);r.redirect('/account')});
 app.post('/account/logout',async(q,r)=>{await db.execute('DELETE FROM oauth_sessions WHERE id=?',[cookies(q.headers.cookie).elid_account]);r.setHeader('Set-Cookie',`elid_account=; HttpOnly; SameSite=Strict; Path=/account; Max-Age=0${q.secure?'; Secure':''}`);r.redirect('/account/login')});
 app.get('/account',auth,async(q,r)=>{const [apps]=await db.execute("SELECT t.client_id,c.name,MAX(t.created_at) last_used,COUNT(*) token_count FROM oauth_tokens t LEFT JOIN oauth_clients c ON c.client_id=t.client_id WHERE t.user_id=? AND t.revoked_at IS NULL AND t.expires_at>NOW() GROUP BY t.client_id,c.name ORDER BY last_used DESC",[q.user.id]);r.send(page(`<nav><b>Elid Account</b><span>${esc(q.user.username)} <form style="display:inline" method=post action=/account/logout><button>Log out</button></form></span></nav><section class=card><h1>Account security</h1><form method=post action=/account/password><input name=current_password type=password placeholder="Current password" required><input name=new_password type=password minlength=12 placeholder="New password (12+ chars)" required><input name=confirm_password type=password minlength=12 placeholder="Confirm new password" required><button>Change password</button></form></section><section class=card><h2>Authorized applications</h2><p>These applications currently have active credentials for your account.</p>${apps.length?`<table><tr><th>Application</th><th>Tokens</th><th>Last issued</th><th></th></tr>${apps.map(a=>`<tr><td>${esc(a.name||a.client_id)}<br><small>${esc(a.client_id)}</small></td><td>${a.token_count}</td><td>${a.last_used}</td><td><form method=post action="/account/apps/${encodeURIComponent(a.client_id)}/revoke"><button>De-authorize</button></form></td></tr>`).join('')}</table>`:'<p>No authorized applications.</p>'}</section>`))});
 app.post('/account/password',auth,async(q,r)=>{if(!q.body.new_password||q.body.new_password.length<12||q.body.new_password!==q.body.confirm_password)return r.status(400).send(page('<main class=card><p class=error>Passwords must match and be at least 12 characters.</p><a href=/account>Back</a></main>'));const [x]=await db.execute('SELECT password_hash FROM oauth_users WHERE id=?',[q.user.id]);if(!x[0]||!(await bcrypt.compare(q.body.current_password,x[0].password_hash)))return r.status(401).send(page('<main class=card><p class=error>Current password is incorrect.</p><a href=/account>Back</a></main>'));await db.execute('UPDATE oauth_users SET password_hash=? WHERE id=?',[await bcrypt.hash(q.body.new_password,12),q.user.id]);await db.execute('UPDATE oauth_tokens SET revoked_at=NOW() WHERE user_id=?',[q.user.id]);r.send(page('<main class=card><p class=ok>Password changed. Existing application sessions were revoked.</p><a href=/account>Continue</a></main>'))});
 app.post('/account/apps/:clientId/revoke',auth,async(q,r)=>{await db.execute('UPDATE oauth_tokens SET revoked_at=NOW() WHERE user_id=? AND client_id=?',[q.user.id,q.params.clientId]);r.redirect('/account')});
}
