import bcrypt from 'bcryptjs';
import {randomToken} from './crypto.mjs';
import {envNumber, rateLimit} from './rate-limit.mjs';
import {snowflake} from './snowflake.mjs';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cookies=v=>Object.fromEntries((v||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2));
const page=(title,body)=>`<!doctype html><meta name=viewport content="width=device-width"><title>${title} - Elid</title><style>:root{color-scheme:dark}body{font:15px system-ui;max-width:1200px;margin:auto;padding:1rem;background:#111;color:#eee}nav,.card{background:#1d1d1d;border:1px solid #444;border-radius:8px;padding:1rem;margin:1rem 0}nav{display:flex;gap:1rem;justify-content:space-between}a{color:#7db7ff}input,button,select{padding:.55rem;margin:.2rem;border-radius:4px;border:1px solid #666;background:#222;color:inherit}button{cursor:pointer}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:.55rem;border-bottom:1px solid #444}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:1rem}.metric{font-size:2rem;font-weight:bold}.muted{color:#aaa}.danger{color:#ff8b8b}</style>${body}`;
export function mountAdmin(app,db){
 const auth=async(req,res,next)=>{const t=cookies(req.headers.cookie).elid_admin;const [ss]=await db.execute("SELECT user_id id,expires_at FROM oauth_sessions WHERE id=? AND session_type='admin' AND expires_at>NOW()",[t]);const s=ss[0];if(!s){await db.execute('DELETE FROM oauth_sessions WHERE id=?',[t]);return res.redirect('/admin/login')}req.admin=s;next()};
 app.get('/admin/login',(q,r)=>r.send(`<!doctype html><meta name=viewport content="width=device-width"><title>Admin sign in - Elid</title><style>:root{color-scheme:dark}body{font:15px system-ui;min-height:100vh;display:grid;place-items:center;margin:0;background:radial-gradient(circle at top,#24334b,#111 60%);color:#eee}.card{width:min(420px,calc(100% - 2rem));box-sizing:border-box;background:#1d1d1dcc;border:1px solid #4b5563;border-radius:14px;padding:2rem;box-shadow:0 20px 70px #0008}h1{margin:.2rem 0 .5rem;font-size:1.8rem}.muted{color:#aaa;line-height:1.5}label{display:block;margin:1rem 0 .35rem}input{box-sizing:border-box;width:100%;padding:.75rem;border:1px solid #667085;border-radius:6px;background:#111;color:#fff;font-size:1rem}button{width:100%;padding:.75rem;margin-top:1.3rem;border:0;border-radius:6px;background:#4f8cff;color:#fff;font-weight:600;font-size:1rem;cursor:pointer}button:hover{background:#6b9dff}.brand{color:#8db7ff;font-weight:700;letter-spacing:.04em}</style><main class=card><div class=brand>ELID ADMIN</div><h1>Admin sign in</h1><p class=muted>Root access only.</p><form method=post><label>Username</label><input name=username autocomplete=username placeholder=Username required autofocus><label>Password</label><input name=password type=password autocomplete=current-password placeholder=Password required><button>Sign in</button></form></main>`));
 app.post('/admin/login',rateLimit({db,windowMs:envNumber('ADMIN_LOGIN_RATE_WINDOW_MS',900000),max:envNumber('ADMIN_LOGIN_RATE_MAX',20),message:'Too many admin login attempts; retry in 15 minutes'}),async(q,r)=>{const [x]=await db.execute('SELECT * FROM oauth_users WHERE username=?',[q.body.username]);if(!x[0]||x[0].username!=='root'||!(await bcrypt.compare(q.body.password,x[0].password_hash)))return r.status(401).send(page('Login','<main class=card><p class=danger>Invalid root credentials.</p><a href=/admin/login>Retry</a></main>'));const t=randomToken();await db.execute("INSERT INTO oauth_sessions(id,user_id,session_type,expires_at) VALUES(?,?,?,DATE_ADD(NOW(),INTERVAL 1 HOUR))",[t,x[0].id,'admin']);r.setHeader('Set-Cookie',`elid_admin=${encodeURIComponent(t)}; HttpOnly; SameSite=Strict; Path=/admin; Max-Age=3600${q.secure?'; Secure':''}`);r.redirect('/admin')});
 app.post('/admin/logout',async(q,r)=>{const t=cookies(q.headers.cookie).elid_admin;await db.execute('DELETE FROM oauth_sessions WHERE id=?',[t]);r.setHeader('Set-Cookie',`elid_admin=; HttpOnly; SameSite=Strict; Path=/admin; Max-Age=0${q.secure?'; Secure':''}`);r.redirect('/admin/login')});
 app.get('/admin',auth,async(q,r)=>{const [[u]]=await db.query('SELECT COUNT(*) n FROM oauth_users'),[[c]]=await db.query('SELECT COUNT(*) n FROM oauth_clients'),[[a]]=await db.query("SELECT COUNT(*) n FROM oauth_tokens WHERE token_type='access' AND revoked_at IS NULL AND expires_at>NOW()"),[[ref]]=await db.query("SELECT COUNT(*) n FROM oauth_tokens WHERE token_type='refresh' AND revoked_at IS NULL AND expires_at>NOW()");const [users]=await db.query('SELECT id,username,created_at FROM oauth_users ORDER BY username');const [clients]=await db.query('SELECT id,client_id,name,redirect_uris,public_client,created_at FROM oauth_clients ORDER BY name');r.send(page('Dashboard',`<nav><b>Elid OAuth Dashboard</b><span><a href=/admin>Dashboard</a> · <a href=/admin/clients>Clients</a> · <form style="display:inline" method=post action=/admin/logout><button>Logout</button></form></span></nav><div class=grid><div class=card><div class=metric>${u.n}</div>Users</div><div class=card><div class=metric>${c.n}</div>Clients</div><div class=card><div class=metric>${a.n}</div>Active access tokens</div><div class=card><div class=metric>${ref.n}</div>Active refresh tokens</div></div><section class=card><h2>Users</h2><form method=post action=/admin/users><input name=username placeholder=Username required><input name=password type=password placeholder="Password (12+ chars)" minlength=12 required><button>Add user</button></form><table><tr><th>Username</th><th>Created</th><th>Actions</th></tr>${users.map(x=>`<tr><td>${esc(x.username)}</td><td>${x.created_at}</td><td><form style="display:inline" method=post action=/admin/users/${x.id}/password><input name=password type=password placeholder="New password" minlength=12 required><button>Change</button></form> <form style="display:inline" method=post action=/admin/users/${x.id}/delete><button ${x.username==='root'?'disabled':''}>Remove</button></form></td></tr>`).join('')}</table></section><section class=card><h2>OAuth clients</h2><p><a href=/admin/clients>Manage clients and redirect URIs →</a></p>${clients.slice(0,5).map(x=>`<p><b>${esc(x.name)}</b> <span class=muted>${esc(x.client_id)}</span></p>`).join('')}</section>`))});
 app.get('/admin/clients',auth,async(q,r)=>{const [clients]=await db.query('SELECT * FROM oauth_clients ORDER BY name');r.send(page('Clients',`<nav><b>OAuth Clients</b><a href=/admin>← Dashboard</a></nav><section class=card><h2>Register client</h2><form method=post action=/admin/clients><input name=name placeholder="Display name" required><input name=client_id placeholder="Client ID" required><input name=redirect_uris placeholder="Redirect URI(s), comma separated" required><label><input type=checkbox name=public_client checked> Public client (PKCE)</label><button>Register</button></form></section><section class=card><table><tr><th>Name</th><th>Client ID</th><th>Redirect URIs</th><th>Type</th><th>Action</th></tr>${clients.map(x=>`<tr><td>${esc(x.name)}</td><td><code>${esc(x.client_id)}</code></td><td>${esc(JSON.parse(x.redirect_uris).join(', '))}</td><td>${x.public_client?'Public':'Confidential'}</td><td><form method=post action=/admin/clients/${x.id}/delete><button>Delete</button></form></td></tr>`).join('')}</table></section>`))});
 app.post('/admin/users',auth,async(q,r)=>{if(!q.body.username||!q.body.password||q.body.password.length<12)return r.status(400).send('Password must be at least 12 characters');await db.execute('INSERT INTO oauth_users(id,username,password_hash) VALUES(?,?,?)',[snowflake(),q.body.username,await bcrypt.hash(q.body.password,12)]);r.redirect('/admin')});
 app.post('/admin/users/:id/password',auth,async(q,r)=>{if(!q.body.password||q.body.password.length<12)return r.status(400).send('Password must be at least 12 characters');await db.execute('UPDATE oauth_users SET password_hash=? WHERE id=?',[await bcrypt.hash(q.body.password,12),q.params.id]);r.redirect('/admin')});
 app.post('/admin/users/:id/delete',auth,async(q,r)=>{const [x]=await db.execute('SELECT username FROM oauth_users WHERE id=?',[q.params.id]);if(x[0]?.username==='root')return r.status(403).send('Root cannot be removed');await db.execute('DELETE FROM oauth_users WHERE id=?',[q.params.id]);r.redirect('/admin')});
 app.post('/admin/clients',auth,async(q,r)=>{const uris=q.body.redirect_uris.split(',').map(x=>x.trim()).filter(Boolean);if(!uris.length)return r.status(400).send('Redirect URI required');await db.execute('INSERT INTO oauth_clients(id,client_id,name,redirect_uris,public_client) VALUES(?,?,?,?,?)',[snowflake(),q.body.client_id,q.body.name,JSON.stringify(uris),q.body.public_client==='on']);r.redirect('/admin/clients')});
 app.post('/admin/clients/:id/delete',auth,async(q,r)=>{await db.execute('DELETE FROM oauth_clients WHERE id=?',[q.params.id]);await db.execute('UPDATE oauth_tokens SET revoked_at=NOW() WHERE client_id=(SELECT client_id FROM oauth_clients WHERE id=?)',[q.params.id]).catch(()=>{});r.redirect('/admin/clients')});
}
